#include <stdlib.h>
#include <string.h>
#ifdef CYARG_FEATURE_HOSTED_REPL
#include <stdio.h>
#include <sysexits.h>
#endif

#include "common.h"
#include "platform_hal.h"
#include "vm.h"
#ifdef CYARG_FEATURE_HOSTED_REPL
#include "hosted.h"
#endif

#ifdef CYARG_FEATURE_HOSTED_REPL
void usageMessage(FILE* destination) {
    FPRINTMSG(destination, "Usage:\n");
    FPRINTMSG(destination, "\tcyarg --lib <dir>\n");
    FPRINTMSG(destination, "\tLaunch a Yarg REPL, using <dir> as the root of the Yarg library.\n");
    FPRINTMSG(destination, "\n");
    FPRINTMSG(destination, "\tcyarg --lib <dir> <path>\n");
    FPRINTMSG(destination, "\tRun a Yarg script at <path>, using <dir> as the root of the Yarg library.\n");
    FPRINTMSG(destination, "\n");
    FPRINTMSG(destination, "\tcyarg --help\n");
    FPRINTMSG(destination, "\tDisplay this help message.\n");
    FPRINTMSG(destination, "\n");
    FPRINTMSG(destination, "\tcyarg --compile <path>\n");
    FPRINTMSG(destination, "\tCompile a Yarg script, reporting any compilation errors.\n");
    FPRINTMSG(destination, "\n");
    FPRINTMSG(destination, "\tcyarg --disassemble <path>\n");
    FPRINTMSG(destination, "\tDisassemble a Yarg script, displaying the generated bytecode.\n");
}

const char* getArgument(int argc, const char* argv[], const char* name) {
    for (int i = 1; i < argc - 1; i++) {
        if (strcmp(argv[i], name) == 0) {
            return argv[i + 1];
        }
    }
    return NULL;
}
#endif

#if defined(CYARG_FEATURE_SELF_HOSTED_REPL)
int main() {
    platform_hal_init();

    initVMMemory();

    ObjString* replPathString = copyString("cyarg.ya", strlen("cyarg.ya"));
    tempRootPush(OBJ_VAL(replPathString));

    initVMRuntime();

    Value discardedResult;
    // Yarg scripts have no mechanism to return a result, so we discard it (it will always be nil).
    bootstrapVM(exec_bootstrap, &discardedResult, replPathString);

    tempRootPop();

    freeVM();
    return 0;
}
#elif defined(CYARG_FEATURE_HOSTED_REPL)
int main(int argc, const char* argv[]) {
    platform_hal_init();

    if (argv[1] && strcmp(argv[1], "--help") == 0) {
        usageMessage(stdout);
        return EX_OK;
    }

    initVMMemory();

    const char* libPath = getArgument(argc, argv, "--lib");

    initVMRuntime();
    vmHost.argc = argc;
    vmHost.argv = argv;
    if (libPath) {
        vm.libraryPath = copyString(libPath, strlen(libPath));
    }

    int returnCode = EX_OK;

    if ((argv[1] && strcmp(argv[1], "--compile") == 0) && argc == 3) {
        Value result;
        returnCode = compileFile(argv[2], &result);
        if (returnCode == EX_SOFTWARE) {
            returnCode = EX_DATAERR;
        }
    } else if ((argv[1] && strcmp(argv[1], "--disassemble") == 0) && argc == 3) {
        returnCode = disassembleFile(argv[2]);
    } else if (argv[1] && strcmp(argv[1], "--lib") == 0 && (argc == 3 || argc == 4)) {
        returnCode = runFile(libPath, "cyarg-hosted.ya");
    } else {
        usageMessage(stderr);
        returnCode = EX_USAGE;
    }

    freeVM();
    return returnCode;
}
#endif
