#include <stdlib.h>
#ifdef CYARG_FEATURE_HOSTED_REPL
#include <string.h>
#include <stdio.h>
#include <sysexits.h>
#endif

#include "common.h"
#include "platform_hal.h"
#include "vm.h"
#ifdef CYARG_FEATURE_HOSTED_REPL
#include "hosted.h"
#endif

#ifdef CYARG_FEATURE_HOSTED_REPL
void usageMessage(FILE* destination) {
    fputs("Usage:\n"
          "\tcyarg --lib <dir>\n"
          "\tLaunch a Yarg REPL, using <dir> as the root of the Yarg library.\n"
          "\n"
          "\tcyarg --lib <dir> <path>\n"
          "\tRun a Yarg script at <path>, using <dir> as the root of the Yarg library.\n"
          "\n"
          "\tcyarg --help\n"
          "\tDisplay this help message.\n"
          "\n"
          "\tcyarg --bootstrap <path>\n"
          "\tExecute a Yarg script, without the language context. For testing of cyarg.\n"
          "\n"
          "\tcyarg --compile <path>\n"
          "\tCompile a Yarg script, reporting any compilation errors.\n"
          "\n"
          "\tcyarg --disassemble <path>\n"
          "\tDisassemble a Yarg script, displaying the generated bytecode.\n"
         , destination);
}

const char* getArgument(int argc, const char* argv[], const char* name) {
    for (int i = 1; i < argc - 1; i++) {
        if (strcmp(argv[i], name) == 0) {
            return argv[i + 1];
        }
    }
    return NULL;
}
#endif

#if defined(CYARG_FEATURE_SELF_HOSTED_REPL)
int main() {
    platform_hal_init();

    initVMMemory();
    initVMRuntime();

    const char script[] = "cyarg.ya";
    ObjString * scriptObj = copyString(script, sizeof(script) - 1);
    tempRootPush(OBJ_VAL(scriptObj));
    bootScript(scriptObj);
    tempRootPop();

    freeVM();
    return 0;
}
#elif defined(CYARG_FEATURE_HOSTED_REPL)
int main(int argc, const char* argv[]) {
    platform_hal_init();

    if (argv[1] && strcmp(argv[1], "--help") == 0) {
        usageMessage(stdout);
        return EX_OK;
    }

    initVMMemory();

    const char* libPath = getArgument(argc, argv, "--lib");

    initVMRuntime();
    vmHost.argc = argc;
    vmHost.argv = argv;
    vmHost.exitCode = EX_OK;
    if (libPath) {
        vm.libraryPath = copyString(libPath, strlen(libPath));
    }
    
    int returnCode = EX_OK;

    if ((argv[1] && strcmp(argv[1], "--compile") == 0) && argc == 3) {
        returnCode = compileFile(argv[2]);
    } else if ((argv[1] && strcmp(argv[1], "--bootstrap") == 0) && argc == 3) {
        returnCode = runHostedFile(NULL, argv[2]);
    } else if ((argv[1] && strcmp(argv[1], "--disassemble") == 0) && argc == 3) {
        returnCode = disassembleFile(argv[2]);
    } else if (argv[1] && strcmp(argv[1], "--lib") == 0 && (argc == 3 || argc == 4)) {
        returnCode = runHostedFile(libPath, "cyarg-hosted.ya");
    } else {
        usageMessage(stderr);
        returnCode = EX_USAGE;
    }

    freeVM();
    return returnCode;
}
#endif
