name: Extras

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-vscode-yarg:
    name: vscode-yarg (tools/build-vscode-yarg.sh)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
    
      - name: Install npm
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install VSCode dependencies
        run: npm install -g @vscode/vsce

      - name: Build VSCode Extension
        run: |
          pushd vscode-yarg
          vsce package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-yarg-extension
          path: vscode-yarg/*.vsix

  build-xcode:
    name: Xcode and bc (tools/build-xcode.sh, test/bc-run.sh)
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.4'
          cache: true
          cache-dependency-path: '**/go.sum'
    
      - name: Build hostyarg
        run: |
          cd hostyarg
          go build -o ../bin/yarg ./cmd/yarg

      - name: Build Xcode project
        run: |
          cd cyarg
          cmake --preset xcode-host
          cmake --build build/xcode-host

      - name: Run Hostyarg Yarg test suite
        run: ./bin/yarg runtests -tests "test/yarg-expect" -interpreter "cyarg/build/xcode-host/Debug/cyarg" -lib "yarg/specimen"
      
      - name: Run BC test suite
        run: |
          cp cyarg/build/xcode-host/Debug/cyarg bin/cyarg
          ./test/bc-run.sh 1000
          echo "build/bc-seeds.txt:"
          cat build/bc-seeds.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yarg-lang-macos-xcode
          path: |
            bin/yarg
            cyarg/build/xcode-host/cyarg
